import { YaourtCharacter } from '@/types';

export const CHARACTERS: YaourtCharacter[] = [
  {
    id: 'le-zen',
    name: 'Le Zen',
    tagline: "L'essentiel, tout simplement.",
    description: 'Nature, crémeux, sans sucre.',
    personality: 'Une personne calme, équilibrée, sûre d\'elle, sans besoin d\'artifices.',
    philosophy: '« Pourquoi en faire plus quand la simplicité suffit ? »',
    traits: ['Simple', 'Authentique', 'Équilibré', 'Discret', 'Sûr de lui'],
    color: 'var(--primary)',
    colorSecondary: 'var(--primary-light)',
    emoji: '🧘',
    productCategory: 'nature', // Will match the product type/category
    model3dUrl: null,
  },
  {
    id: 'le-copain',
    name: 'Le Copain',
    tagline: 'Doux, sucré et toujours de bonne compagnie.',
    description: 'Yaourt sucré simple.',
    personality: 'Le bon copain qui plaît facilement, ne cherche pas à impressionner et qu\'on choisit pour le côté familier.',
    philosophy: '« Pas besoin d\'en faire des tonnes pour passer un bon moment. »',
    traits: ['Sympathique', 'Accessible', 'Chaleureux', 'Réconfortant', 'Sans prétention'],
    color: 'var(--info)',
    colorSecondary: 'var(--info-light)',
    emoji: '🤝',
    productCategory: 'simple',
    model3dUrl: null,
  },
  {
    id: 'le-gourmand',
    name: 'Le Gourmand',
    tagline: 'Crémeux, sucré, généreusement onctueux.',
    description: 'Yaourt sucré crémeux.',
    personality: 'Celui qui assume son côté plaisir et aime les choses douces, généreuses et onctueuses.',
    philosophy: '« La vie est trop courte pour se priver de douceur. »',
    traits: ['Gourmand', 'Séducteur', 'Généreux', 'Plaisantin', 'Un peu charmeur'],
    color: 'var(--pink)',
    colorSecondary: 'var(--pink-light)',
    emoji: '😋',
    productCategory: 'cremeux', // Might need adjusting to match exact backend category
    model3dUrl: null,
  },
  {
    id: 'le-creatif',
    name: 'Le Créatif',
    tagline: 'Crémeux, croustillant, avec des céréales faites maison.',
    description: 'Yaourt crémeux + céréales maison.',
    personality: 'Celui qui aime faire les choses lui-même, soigne les détails et apporte sa touche personnelle.',
    philosophy: '« Les meilleures choses sont celles qu\'on prend le temps de faire. »',
    traits: ['Créatif', 'Authentique', 'Curieux', 'Soigneux', 'Généreux'],
    color: 'var(--warning)',
    colorSecondary: 'var(--warning-strong)',
    emoji: '🎨',
    productCategory: 'cereales',
    model3dUrl: null,
  },
  {
    id: 'le-dynamique',
    name: 'Le Dynamique',
    tagline: 'Crémeux + fruits frais, apporte de la couleur et de la fraîcheur.',
    description: 'Yaourt crémeux aux fruits frais.',
    personality: 'Le personnage dynamique de la bande, qui aime la fraîcheur et les associations qui réveillent.',
    philosophy: '« Mettez de la couleur dans votre journée ! »',
    traits: ['Dynamique', 'Joyeux', 'Frais', 'Coloré', 'Optimiste'],
    color: 'var(--success)',
    colorSecondary: 'var(--success-light)',
    emoji: '⚡',
    productCategory: 'fruits',
    model3dUrl: null,
  },
];
